### ISSUE TITLE
SkyReels Broken After Hunyuan I2V Update

### ISSUE THREAD

**Issue by pftq** [kijai/ComfyUI-HunyuanVideoWrapper#425]
Seems like the update for I2V broke something for SkyReels.  I'm getting this error now:

HyVideoSampler
Given groups=1, weight of size [3072, 32, 1, 2, 2], expected input[2, 33, 49, 64, 64] to have 32 channels, but got 33 channels instead

**Comment by kijai** [comment]
Are you on very latest version? I thought I fixed that earlier.

**Comment by pftq** [comment]
Let me check - I updated this morning for I2V.

**Comment by pftq** [comment]
Yeah I just updated and got the error again

**Comment by kijai** [comment]
> Yeah I just updated and got the error again

Updated how exactly? I just loaded the example workflow for Skyreels and it's working fine with the current code.

**Comment by pftq** [comment]
Through Comfyui custom nodes manager

![Image](https://github.com/user-attachments/assets/611301d1-35fa-42af-a627-750384010fcb)
(I'm downgraded back down right now to finish a render)

**Comment by kijai** [comment]
Manager has been notoriously annoying lately tbh.. maybe I need to bump the version again.

**Comment by pftq** [comment]
I'm getting this again but only on the latest fixed I2V model.  It seems to be specific to the id fix, as the older i2v from yesterday doesn't trigger this error.  I also have issues running their official github one which has model/weights mismatch error, so it's possible their model update itself is broken https://github.com/Tencent/HunyuanVideo-I2V/issues/8#issuecomment-2707199199
```
HyVideoSampler
Given groups=1, weight of size [3072, 16, 1, 2, 2], expected input[1, 32, 31, 88, 156] to have 16 channels, but got 32 channels instead
```

**Comment by kijai** [comment]
The fixed model doesn't work yet.

**Comment by pftq** [comment]
Ok good to confirm, thanks

**Comment by pftq** [comment]
What should be the i2vmode on Skyreels with the new update? It shows as disabled now on the old workflows.

**Comment by kijai** [comment]
> What should be the i2vmode on Skyreels with the new update? It shows as disabled now on the old workflows.
> 
> Edit: Tried both and getting this error again on Skyreels.
> 
> ```
> HyVideoSampler
> 
> Given groups=1, weight of size [3072, 32, 1, 2, 2], expected input[2, 33, 7, 136, 240] to have 32 channels, but got 33 channels instead
> ```

That should be fixed now, dynamic should be the old behaviour but stability should also work, no idea if it's good though.

**Comment by pftq** [comment]
Ok - do you think you could default it to dynamic then for old workflows not to break? Would be helpful since it's a habit to drop in workflows from other MP4s and tweak from there.

**Comment by kijai** [comment]
> Ok thanks - do you think you could default it to dynamic then for old workflows not to break? Would be helpful since it's a habit to drop in workflows from other MP4s and tweak from there.

I don't think it makes a huge difference really... the default for the first I2V model would be same as stability, which is why I left that as default, but might make sense to be dynamic as it doesn't do anything extra.

**Comment by pftq** [comment]
No I mean as opposed to "disabled" being the default when an older workflow is pulled up.  I'll probably forget at some point or other people might run into the same error and not realize it's from that being added as a field.
![Image](https://github.com/user-attachments/assets/bbc03cc8-7874-46c0-b51a-4bff72000be4)

**Comment by kijai** [comment]
> No I mean as opposed to "disabled" being the default when an older workflow is pulled up. I'll probably forget at some point or other people might run into the same error and not realize it's from that being added as a field. Same with riflex - the default is "" even though it shows 0 on the GUI and throws an error on old workflows (has to be re-entered as 0 to fix). ![Image](https://github.com/user-attachments/assets/bbc03cc8-7874-46c0-b51a-4bff72000be4)

Oh yeah that was an oversight, changed it to "dynamic" now. RifleX already was 0 and always has been though, but ComfyUI gets all kinds of messed up with node updates still...

**Comment by pftq** [comment]
Great, thanks

**Comment by pftq** [comment]
Skyreels broken again after i2v-fix working.  I checked and redownloaded the wrapper as well via git clone.
```
HyVideoSampler
Given groups=1, weight of size [3072, 32, 1, 2, 2], expected input[2, 33, 49, 64, 64] to have 32 channels, but got 33 channels instead
```

**Comment by kijai** [comment]
> Skyreels broken again after i2v-fix working. I checked and redownloaded the wrapper as well via git clone. I am reverting back to 1.03 for now (last working version for Skyreels)
> 
> ```
> HyVideoSampler
> Given groups=1, weight of size [3072, 32, 1, 2, 2], expected input[2, 33, 49, 64, 64] to have 32 channels, but got 33 channels instead
> ```

Are you sure? Nothing has changed about that since I fixed it, and it still works for me with current code.

**Comment by pftq** [comment]
Yeah - it worked on 1.0.5, then updating to 1.0.6 (latest) gets the error.  Also while on the subject, I think if you add a case for accepting "" as input being the same as 0, that'll give backwards compatibility to old workflows without throwing an error.  It's a silent error otherwise so it's a bit insidious.
https://youtu.be/z0YdACfQeic

**Comment by kijai** [comment]
> Yeah - it worked on 1.0.5, then updating to 1.0.6 (latest) gets the error. Also while on the subject, I think if you add a case for accepting "" as input being the same as 0, that'll give backwards compatibility to old workflows without throwing an error. It's a silent error otherwise so it's a bit insidious. https://youtu.be/z0YdACfQeic

Latest on manager isn't actually latest code though, should be on nightly for that.

**Comment by pftq** [comment]
Still getting this.  On nightly 1.07

![Image](https://github.com/user-attachments/assets/3086ae0e-e02b-4f95-b9c0-cdce9f124ab3)

**Comment by pftq** [comment]
Skyreels broken again for me on 1.08 but there's two versions of 1.08 - one that works and one that doesn't (I have two different servers).  The one that works is 1.08 but doesn't have the "Update 5" in the readme.  The one that is doesn't work has the "Update 5" with the LORAs, although it still says 1.08 as the version (I'm guessing two updates were pushed on the same day/version number).

This is the error:
```
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 1433, in process
    out_latents = model["pipe"](
                  ^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 555, in __call__
    prompt_embeds = torch.cat([negative_prompt_embeds, prompt_embeds])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 73 but got size 77 for tensor number 1 in the list.
```

**Comment by pftq** [comment]
Got it fixed with the new update from here https://github.com/kijai/ComfyUI-HunyuanVideoWrapper/issues/445

**Comment by pftq** [comment]
Actually still broken.  No errors but it ends up rendering a black screen instead.  Last working version I'm reverting to is the 1.08 without the Update 5 in the readme.
